export class User {
	constructor(
	public _id : string,
	public name : string,
	public f_surname : string,
	public s_surname : string,
	public curp : string,
	public nid : string,
	public civil_status : string,
	public nacionality : string,
	public birth_state : string,
	public gender : string,
	public birth_date : string,
	public lang_m : string,
	public type_doc_id : string,
	public folio_doc : string,
	public email : string,
	public password : string,
	public role : string,
	public description_role : string,
	public image : string,
	public street : string,
	public between_street_1 : string,
	public between_street_2 : string,
	public number_home : string,
	public apple : string,
	public lote : string,
	public number_int : string,
	public department : string,
	public other_reference : string,
	public cp : string,
	public colony : string,
	public federal_entity : string,
	public municipality : string,
	public location : string,
	public active : boolean,
	public id_alumno_tutor : string,
	public main_tutor : string,
	public grade: string,
	public cicle: string,
	public gettoken : string
		){}   
}

